
const REFRESH = 'REFRESH';

const MAKE_SHOOT = 'MAKE_SHOOT';

const CHANGE_GAME_BEGIN = 'CHANGE_GAME_BEGIN';

const GENERATE_FIELD = 'GENERATE_FIELD';

export { REFRESH, MAKE_SHOOT, CHANGE_GAME_BEGIN, GENERATE_FIELD };